<?php

use App\Models\User;
use Database\Seeders\RoleSeeder;
use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

test('admin can export a list pdf with applied filters metadata', function () {
    (new RoleSeeder)->run();
    (new UserSeeder)->run();

    $admin = User::query()->where('email', 'admin@rosewoodroyale.com')->firstOrFail();

    $response = $this->actingAs($admin, 'sanctum')
        ->postJson('/api/list-exports/pdf', [
            'title' => 'Buildings',
            'filename' => 'buildings.pdf',
            'landscape' => true,
            'generated_by' => 'Admin User',
            'columns' => [
                ['field' => 'building_name', 'header' => 'Building Name'],
                ['field' => 'location', 'header' => 'Location'],
            ],
            'rows' => [
                ['building_name' => 'Rosewood Tower', 'location' => 'Yangon'],
            ],
            'filters' => [
                ['label' => 'Search', 'value' => 'Rosewood'],
            ],
        ]);

    $response->assertOk()
        ->assertHeader('content-type', 'application/pdf')
        ->assertHeader('content-disposition', 'attachment; filename="buildings.pdf"');

    expect(str_starts_with($response->getContent(), '%PDF'))->toBeTrue();
});

test('list export view uses shared chrome and optional column layout metadata', function () {
    $html = view('exports.list', [
        'title' => 'Invoices',
        'columns' => [
            ['field' => 'invoice_number', 'header' => 'Invoice #', 'width' => '10%', 'nowrap' => true],
            ['field' => 'customer_name', 'header' => 'Customer', 'width' => '22%'],
            ['field' => 'invoice_total', 'header' => 'Total (MMK)', 'width' => '14%', 'align' => 'right', 'nowrap' => true],
            ['field' => 'payment_status', 'header' => 'Status', 'width' => '10%', 'nowrap' => true],
        ],
        'rows' => [
            [
                'invoice_number' => 'INV-001',
                'customer_name' => 'Jane Doe',
                'invoice_total' => '100,000',
                'payment_status' => 'Overdue',
            ],
        ],
        'filters' => [],
        'generatedBy' => 'Admin',
        'generatedAt' => '2026-01-01 12:00',
        'landscape' => true,
    ])->render();

    expect($html)->toContain('list-col--invoice_number')
        ->and($html)->toContain('list-col--align-right')
        ->and($html)->toContain('list-col--nowrap')
        ->and($html)->toContain('width: 10%;')
        ->and($html)->toContain('Overdue')
        ->and($html)->not->toContain('Late Fee Rule')
        ->and($html)->toContain('Generated By')
        ->and($html)->toContain('pdf-sheet--list')
        ->and($html)->toContain('width: 100% !important')
        ->and($html)->toContain('list-export-filters')
        ->and($html)->not->toContain('.pdf-sheet--list { width: 297mm');
});

test('shared list export does not hardcode invoice widths onto unrelated modules', function () {
    $html = view('exports.list', [
        'title' => 'Payments',
        'columns' => [
            ['field' => 'customer_name', 'header' => 'Customer'],
            ['field' => 'paid', 'header' => 'Paid'],
        ],
        'rows' => [
            ['customer_name' => 'Jane Doe', 'paid' => '50,000'],
        ],
        'filters' => [],
        'generatedBy' => 'Admin',
        'generatedAt' => '2026-01-01 12:00',
        'landscape' => true,
    ])->render();

    expect($html)->toContain('list-col--customer_name')
        ->and($html)->not->toContain('width: 22%;')
        ->and($html)->toContain('Payments');
});
