services:
  - type: web
    name: em-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: RUN_MIGRATIONS
        value: "true"
      - key: FRONTEND_URL
        sync: false
