<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        {!! file_get_contents(resource_path('documents/contract-document.css')) !!}

        @page {
            size: {{ $landscape ? 'A4 landscape' : 'A4 portrait' }};
            margin: 12mm;
        }

        body {
            background: #fff;
            margin: 0;
        }

        .pdf-sheet.pdf-sheet--list {
            width: {{ $landscape ? '297mm' : '210mm' }};
            max-width: {{ $landscape ? '297mm' : '210mm' }};
            min-height: auto;
            margin: 0 auto;
            padding: 12mm;
            box-shadow: none;
            border: none;
        }

        .list-export-meta {
            margin: 0 0 1rem;
            font-size: 9pt;
            color: #6b6560;
        }

        .list-export-filters {
            margin: 0 0 1.25rem;
            padding: 0;
            list-style: none;
            font-size: 9pt;
            color: #6b6560;
        }

        .list-export-filters li {
            margin: 0.15rem 0;
        }

        .pdf-sheet--list .doc-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
            font-size: 8.5pt;
        }

        .pdf-sheet--list .doc-table thead {
            display: table-header-group;
        }

        .pdf-sheet--list .doc-table th,
        .pdf-sheet--list .doc-table td {
            border: 1px solid rgba(28, 28, 28, 0.15);
            padding: 4px 6px;
            vertical-align: top;
            text-align: left;
            overflow-wrap: break-word;
        }

        .pdf-sheet--list .doc-table th {
            background: rgba(122, 49, 73, 0.08);
            font-weight: 600;
        }

        .pdf-sheet--list .doc-table tr {
            break-inside: avoid;
            page-break-inside: avoid;
        }

        .pdf-sheet--list .list-col--invoice_number {
            width: 10%;
            white-space: nowrap;
        }

        .pdf-sheet--list .list-col--customer_name {
            width: 22%;
        }

        .pdf-sheet--list .list-col--building_name {
            width: 20%;
        }

        .pdf-sheet--list .list-col--room_number {
            width: 6%;
            white-space: nowrap;
        }

        .pdf-sheet--list .list-col--invoice_total {
            width: 14%;
            white-space: nowrap;
        }

        .pdf-sheet--list .list-col--issued_date,
        .pdf-sheet--list .list-col--due_date {
            width: 9%;
            white-space: nowrap;
        }

        .pdf-sheet--list .list-col--payment_status {
            width: 10%;
            white-space: nowrap;
        }

        .pdf-sheet--list .pdf-foot-page::after {
            content: 'Page ' counter(page);
        }

        @media print {
            html {
                counter-reset: none;
            }
        }
    </style>
</head>
<body>
    <article id="pdf-print" class="pdf-sheet pdf-sheet--list">
        <div class="pdf-document-lead">
            <header class="pdf-head">
                <div class="pdf-head-row">
                    <div class="pdf-brand">
                        @php
                            $logoPath = resource_path('documents/logo-dark.jpg');
                            $logoSrc = is_file($logoPath)
                                ? 'data:image/jpeg;base64,'.base64_encode((string) file_get_contents($logoPath))
                                : '';
                        @endphp
                        @if ($logoSrc)
                            <img src="{{ $logoSrc }}" alt="Rosewood Royale" class="pdf-logo">
                        @endif
                        <div class="pdf-brand-text">
                            <p class="pdf-company">Rosewood Royale Residences</p>
                            <p class="pdf-company-sub">Residences &amp; Property Management</p>
                        </div>
                    </div>
                    <div class="pdf-head-meta">
                        <div class="pdf-meta-item">
                            <span class="pdf-meta-label">Generated</span>
                            <span class="pdf-meta-value">{{ $generatedAt }}</span>
                        </div>
                        <div class="pdf-meta-item">
                            <span class="pdf-meta-label">Generated By</span>
                            <span class="pdf-meta-value">{{ $generatedBy }}</span>
                        </div>
                    </div>
                </div>
                <h1 class="pdf-doc-title">{{ $title }}</h1>
                <div class="pdf-rule pdf-rule--accent"></div>
            </header>
        </div>

        @if (! empty($filters))
            <ul class="list-export-filters">
                @foreach ($filters as $filter)
                    <li><strong>{{ $filter['label'] }}:</strong> {{ $filter['value'] !== '' && $filter['value'] !== null ? $filter['value'] : 'All' }}</li>
                @endforeach
            </ul>
        @endif

        <section class="pdf-block">
            <div class="doc-table-wrap">
                <table class="doc-table">
                    <thead>
                        <tr>
                            @foreach ($columns as $column)
                                @php
                                    $columnClass = 'list-col list-col--'.preg_replace('/[^a-z0-9_-]/i', '-', $column['field']);
                                @endphp
                                <th class="{{ $columnClass }}">{{ $column['header'] }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($rows as $row)
                            <tr>
                                @foreach ($columns as $column)
                                    @php
                                        $columnClass = 'list-col list-col--'.preg_replace('/[^a-z0-9_-]/i', '-', $column['field']);
                                    @endphp
                                    <td class="{{ $columnClass }}">{{ $row[$column['field']] ?? '' }}</td>
                                @endforeach
                            </tr>
                        @empty
                            <tr>
                                <td colspan="{{ max(count($columns), 1) }}">No records found.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </section>

        <footer class="pdf-foot">
            <div class="pdf-foot-row">
                <span>Confidential</span>
                <span class="pdf-foot-page"></span>
                <span>{{ $title }}</span>
            </div>
        </footer>
    </article>
</body>
</html>
